<?xml version="1.0" encoding="utf-8"?><Database Name="Laenutus" EntityNamespace="DBA" ContextNamespace="DBA" Class="LINQtoSQLclassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TAAVISILDEBERG\SQLEXPRESS;Initial Catalog=Laenutus;Integrated Security=True" SettingsObjectName="LendingTracker.Properties.Settings" SettingsPropertyName="LendingTrackerDBConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Catalog" Member="Movies">
    <Type Name="Movie">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Genre" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Descr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Catalog_Rental" Member="Rentals" ThisKey="id" OtherKey="MovieID" Type="Rental" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Storage="_Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Storage="_Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="true" />
      <Column Name="ID_code" Member="IDCode" Storage="_IDnumber" Type="System.Int64" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VIP" Type="System.Boolean" CanBeNull="false" />
      <Column Name="Problematic" Type="System.Boolean" CanBeNull="false" />
      <Column Name="DocumentNumber" Type="System.String" CanBeNull="true" />
      <Association Name="Client_Rental" Member="Rentals" ThisKey="id" OtherKey="ClientID" Type="Rental" />
    </Type>
  </Table>
  <Table Name="dbo.Rentals" Member="Rentals">
    <Type Name="Rental">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Notify" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Catalog_Rental" Member="Movie" Storage="_Catalog" ThisKey="MovieID" OtherKey="id" Type="Movie" IsForeignKey="true" />
      <Association Name="Client_Rental" Member="Client" ThisKey="ClientID" OtherKey="id" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>